import { FurnitureItem } from '@/types';

export const FURNITURE: FurnitureItem[] = [
  {
    id: 'sofa-3seater',
    name: '三人沙发',
    category: 'sofa',
    defaultMaterialId: 'fabric-gray',
    availableMaterials: ['fabric-beige', 'fabric-gray', 'fabric-navy', 'fabric-terracotta', 'fabric-emerald', 'leather-black', 'leather-brown'],
    boundingBox: { width: 2.2, depth: 0.9, height: 0.85 },
    geometryType: 'custom',
    geometryParams: {},
  },
  {
    id: 'sofa-2seater',
    name: '双人沙发',
    category: 'sofa',
    defaultMaterialId: 'fabric-beige',
    availableMaterials: ['fabric-beige', 'fabric-gray', 'fabric-navy', 'fabric-terracotta', 'leather-black'],
    boundingBox: { width: 1.6, depth: 0.85, height: 0.8 },
    geometryType: 'custom',
    geometryParams: {},
  },
  {
    id: 'sofa-lounge',
    name: '贵妃椅',
    category: 'sofa',
    defaultMaterialId: 'fabric-emerald',
    availableMaterials: ['fabric-emerald', 'fabric-navy', 'leather-brown'],
    boundingBox: { width: 0.9, depth: 1.8, height: 0.8 },
    geometryType: 'custom',
    geometryParams: {},
  },
  {
    id: 'chair-dining',
    name: '餐椅',
    category: 'chair',
    defaultMaterialId: 'wood-light',
    availableMaterials: ['wood-light', 'wood-dark', 'fabric-gray', 'fabric-beige'],
    boundingBox: { width: 0.5, depth: 0.5, height: 0.9 },
    geometryType: 'custom',
    geometryParams: {},
  },
  {
    id: 'chair-armchair',
    name: '扶手椅',
    category: 'chair',
    defaultMaterialId: 'fabric-terracotta',
    availableMaterials: ['fabric-terracotta', 'fabric-navy', 'leather-black', 'leather-brown'],
    boundingBox: { width: 0.75, depth: 0.8, height: 0.95 },
    geometryType: 'custom',
    geometryParams: {},
  },
  {
    id: 'chair-office',
    name: '办公椅',
    category: 'chair',
    defaultMaterialId: 'leather-black',
    availableMaterials: ['leather-black', 'fabric-gray', 'metal-brushed'],
    boundingBox: { width: 0.65, depth: 0.65, height: 1.1 },
    geometryType: 'custom',
    geometryParams: {},
  },
  {
    id: 'table-coffee',
    name: '茶几',
    category: 'table',
    defaultMaterialId: 'wood-light',
    availableMaterials: ['wood-light', 'wood-dark', 'marble-white', 'metal-gold'],
    boundingBox: { width: 1.2, depth: 0.6, height: 0.45 },
    geometryType: 'box',
    geometryParams: { width: 1.2, depth: 0.6, height: 0.05 },
  },
  {
    id: 'table-dining',
    name: '餐桌',
    category: 'table',
    defaultMaterialId: 'wood-dark',
    availableMaterials: ['wood-dark', 'wood-light', 'marble-white', 'glass-clear'],
    boundingBox: { width: 1.8, depth: 0.9, height: 0.75 },
    geometryType: 'box',
    geometryParams: { width: 1.8, depth: 0.9, height: 0.08 },
  },
  {
    id: 'table-side',
    name: '边桌',
    category: 'table',
    defaultMaterialId: 'metal-gold',
    availableMaterials: ['metal-gold', 'metal-brushed', 'wood-light', 'marble-white'],
    boundingBox: { width: 0.5, depth: 0.5, height: 0.55 },
    geometryType: 'box',
    geometryParams: { width: 0.5, depth: 0.5, height: 0.05 },
  },
  {
    id: 'bed-double',
    name: '双人床',
    category: 'bed',
    defaultMaterialId: 'fabric-gray',
    availableMaterials: ['fabric-gray', 'fabric-beige', 'leather-brown', 'wood-light'],
    boundingBox: { width: 1.8, depth: 2.0, height: 0.5 },
    geometryType: 'custom',
    geometryParams: {},
  },
  {
    id: 'bed-single',
    name: '单人床',
    category: 'bed',
    defaultMaterialId: 'wood-light',
    availableMaterials: ['wood-light', 'wood-dark', 'fabric-gray'],
    boundingBox: { width: 1.2, depth: 2.0, height: 0.45 },
    geometryType: 'custom',
    geometryParams: {},
  },
  {
    id: 'lamp-floor',
    name: '落地灯',
    category: 'lamp',
    defaultMaterialId: 'metal-gold',
    availableMaterials: ['metal-gold', 'metal-brushed', 'wood-dark'],
    boundingBox: { width: 0.4, depth: 0.4, height: 1.6 },
    geometryType: 'custom',
    geometryParams: {},
  },
  {
    id: 'lamp-table',
    name: '台灯',
    category: 'lamp',
    defaultMaterialId: 'metal-brushed',
    availableMaterials: ['metal-brushed', 'metal-gold', 'glass-clear'],
    boundingBox: { width: 0.25, depth: 0.25, height: 0.5 },
    geometryType: 'custom',
    geometryParams: {},
  },
  {
    id: 'decor-plant',
    name: '绿植盆栽',
    category: 'decoration',
    defaultMaterialId: 'wood-light',
    availableMaterials: ['wood-light', 'ceramic-white'],
    boundingBox: { width: 0.4, depth: 0.4, height: 0.8 },
    geometryType: 'custom',
    geometryParams: {},
  },
  {
    id: 'decor-vase',
    name: '装饰花瓶',
    category: 'decoration',
    defaultMaterialId: 'marble-white',
    availableMaterials: ['marble-white', 'metal-gold', 'glass-clear'],
    boundingBox: { width: 0.2, depth: 0.2, height: 0.4 },
    geometryType: 'cylinder',
    geometryParams: { radiusTop: 0.08, radiusBottom: 0.1, height: 0.35 },
  },
  {
    id: 'decor-rug',
    name: '地毯',
    category: 'decoration',
    defaultMaterialId: 'fabric-beige',
    availableMaterials: ['fabric-beige', 'fabric-gray', 'fabric-terracotta'],
    boundingBox: { width: 2.0, depth: 1.4, height: 0.02 },
    geometryType: 'box',
    geometryParams: { width: 2.0, depth: 1.4, height: 0.02 },
  },
];

export const getFurnitureById = (id: string): FurnitureItem | undefined => {
  return FURNITURE.find(f => f.id === id);
};

export const getFurnitureByCategory = (category: string): FurnitureItem[] => {
  return FURNITURE.filter(f => f.category === category);
};
